name: Construire le conteneur et le publier sur le registre GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Se connecter au GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.FLO_TOKEN }}

      - name: Construire le conteneur et le publier sur le registre GitHub Packages
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/flolev/ue19-lab-05/my-app:latest

      - name: Scanner l'image Docker pour les vulnerabilites
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/flolev/ue19-lab-05/my-app:latest
